apply plugin: 'com.android.application'

android {
    namespace "com.obsidium.bettermanual"
    compileSdkVersion 34

    lint {
        // Use 'OldTargetApi' or 'ExpiredTargetSdkVersion'
        disable 'OldTargetApi'
        // To prevent lint from stopping your build:
        abortOnError false
    }

    defaultConfig {
        applicationId "com.obsidium.bettermanual"
        minSdkVersion 10
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 10
        versionCode 7
        versionName "2.0.0"
        archivesBaseName = "BetterManual-${versionName}"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
}

dependencies {
    compileOnly 'com.github.ma1co.OpenMemories-Framework:stubs:-SNAPSHOT'
    implementation 'com.github.ma1co.OpenMemories-Framework:framework:-SNAPSHOT'
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
}
